name: pytest

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# This job installs dependencies and runs tests
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Prepare environment
      run: |
        source prepare-env.sh

    # Running pytest
    - name: Running pytest
      run: |
        source .venv/bin/activate
        python3 -m pytest